In [200]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [201]:
df = pd.read_csv('googleplaystore.csv')

In [202]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [203]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [205]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [206]:
df.shape

(10841, 13)

In [207]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [208]:
# Generating 10 random samples from the dataset
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4474,Parallel Space - Multiple accounts & Two face,PERSONALIZATION,4.6,3062845,7.4M,"100,000,000+",Free,0,Everyone,Personalization,"August 3, 2018",4.0.8552,4.0.3 and up
10216,MB Notifications for FB (Free),SOCIAL,3.9,3047,1.5M,"100,000+",Free,0,Teen,Social,"April 29, 2015",1.17.0,2.3 and up
1861,Summoners War,GAME,4.3,2045554,28M,"50,000,000+",Free,0,Teen,Role Playing,"July 30, 2018",4.0.1,4.0.3 and up
5291,Weapon AK-74 Live Wallpaper,PERSONALIZATION,3.3,25,46M,"1,000+",Free,0,Everyone,Personalization,"March 28, 2017",1.2,4.0.3 and up
4228,I Screen Dialer,TOOLS,4.1,8137,3.9M,"1,000,000+",Free,0,Everyone,Tools,"February 25, 2018",1.11,4.3 and up
9681,Urban Car Simulator,FAMILY,4.2,23292,20M,"1,000,000+",Free,0,Everyone,Simulation,"September 19, 2017",1.4,2.3 and up
2032,Puzzle Kids - Animals Shapes and Jigsaw Puzzles,FAMILY,4.6,1109,52M,"1,000,000+",Free,0,Everyone,Educational;Brain Games,"July 18, 2018",1.0.6,4.1 and up
6191,Background Changer & Eraser,PHOTOGRAPHY,4.0,2076,11M,"500,000+",Free,0,Teen,Photography,"May 21, 2018",2.5,4.1 and up
4937,AC Remote for Samsung - NOW FREE,TOOLS,3.7,566,27M,"100,000+",Free,0,Everyone,Tools,"July 30, 2018",6.1.7,4.2 and up
5683,SMS Au revoir,FAMILY,NaN,17,1.7M,"5,000+",Free,0,Everyone,Entertainment,"January 15, 2018",2.0.0,4.0 and up

In [209]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [210]:
# Converting some of the feature into the numerical which is in object

In [211]:
df['Reviews'].head()

0       159
1       967
2     87510
3    215644
4       967
Name: Reviews, dtype: object

In [212]:
df['Reviews'].dtypes

dtype('O')

In [213]:
df.Reviews.str.isnumeric().sum()

10840

In [214]:
df['Reviews'].shape

(10841,)

In [215]:
# There is only one value which is not the numerical value and all other values are the numerical value
df['Reviews'].shape-df.Reviews.str.isnumeric().sum()

array([1])

In [216]:
df[ ~df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [217]:
df_copy = df.copy()

In [218]:
df_copy=df_copy.drop(df_copy.index[10472])

In [219]:
df_copy.shape

(10840, 13)

In [220]:
df_copy['Reviews']=df_copy['Reviews'].astype(int)

In [221]:
df_copy['Reviews'].dtype

dtype('int32')

In [222]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int32
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), int32(1), object(11)
memory usage: 1.1+ MB

In [223]:
df_copy['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [224]:
df_copy['Size'] = df_copy['Size'].str.replace('M','000')

In [225]:
df_copy['Size'] = df_copy['Size'].str.replace('k',' ')

In [226]:
df_copy['Size'].unique()

array(['19000', '14000', '8.7000', '25000', '2.8000', '5.6000', '29000',
       '33000', '3.1000', '28000', '12000', '20000', '21000', '37000',
       '2.7000', '5.5000', '17000', '39000', '31000', '4.2000', '7.0000',
       '23000', '6.0000', '6.1000', '4.6000', '9.2000', '5.2000', '11000',
       '24000', 'Varies with device', '9.4000', '15000', '10000',
       '1.2000', '26000', '8.0000', '7.9000', '56000', '57000', '35000',
       '54000', '201 ', '3.6000', '5.7000', '8.6000', '2.4000', '27000',
       '2.5000', '16000', '3.4000', '8.9000', '3.9000', '2.9000', '38000',
       '32000', '5.4000', '18000', '1.1000', '2.2000', '4.5000', '9.8000',
       '52000', '9.0000', '6.7000', '30000', '2.6000', '7.1000', '3.7000',
       '22000', '7.4000', '6.4000', '3.2000', '8.2000', '9.9000',
       '4.9000', '9.5000', '5.0000', '5.9000', '13000', '73000', '6.8000',
       '3.5000', '4.0000', '2.3000', '7.2000', '2.1000', '42000',
       '7.3000', '9.1000', '55000', '23 ', '6.5000', '1.5000', '7.5000',
       '51000', '41000', '48000', '8.5000', '46000', '8.3000', '4.3000',
       '4.7000', '3.3000', '40000', '7.8000', '8.8000', '6.6000',
       '5.1000', '61000', '66000', '79 ', '8.4000', '118 ', '44000',
       '695 ', '1.6000', '6.2000', '18 ', '53000', '1.4000', '3.0000',
       '5.8000', '3.8000', '9.6000', '45000', '63000', '49000', '77000',
       '4.4000', '4.8000', '70000', '6.9000', '9.3000', '10.0000',
       '8.1000', '36000', '84000', '97000', '2.0000', '1.9000', '1.8000',
       '5.3000', '47000', '556 ', '526 ', '76000', '7.6000', '59000',
       '9.7000', '78000', '72000', '43000', '7.7000', '6.3000', '334 ',
       '34000', '93000', '65000', '79000', '100000', '58000', '50000',
       '68000', '64000', '67000', '60000', '94000', '232 ', '99000',
       '624 ', '95000', '8.5 ', '41 ', '292 ', '11 ', '80000', '1.7000',
       '74000', '62000', '69000', '75000', '98000', '85000', '82000',
       '96000', '87000', '71000', '86000', '91000', '81000', '92000',
       '83000', '88000', '704 ', '862 ', '899 ', '378 ', '266 ', '375 ',
       '1.3000', '975 ', '980 ', '4.1000', '89000', '696 ', '544 ',
       '525 ', '920 ', '779 ', '853 ', '720 ', '713 ', '772 ', '318 ',
       '58 ', '241 ', '196 ', '857 ', '51 ', '953 ', '865 ', '251 ',
       '930 ', '540 ', '313 ', '746 ', '203 ', '26 ', '314 ', '239 ',
       '371 ', '220 ', '730 ', '756 ', '91 ', '293 ', '17 ', '74 ', '14 ',
       '317 ', '78 ', '924 ', '902 ', '818 ', '81 ', '939 ', '169 ',
       '45 ', '475 ', '965 ', '90000', '545 ', '61 ', '283 ', '655 ',
       '714 ', '93 ', '872 ', '121 ', '322 ', '1.0000', '976 ', '172 ',
       '238 ', '549 ', '206 ', '954 ', '444 ', '717 ', '210 ', '609 ',
       '308 ', '705 ', '306 ', '904 ', '473 ', '175 ', '350 ', '383 ',
       '454 ', '421 ', '70 ', '812 ', '442 ', '842 ', '417 ', '412 ',
       '459 ', '478 ', '335 ', '782 ', '721 ', '430 ', '429 ', '192 ',
       '200 ', '460 ', '728 ', '496 ', '816 ', '414 ', '506 ', '887 ',
       '613 ', '243 ', '569 ', '778 ', '683 ', '592 ', '319 ', '186 ',
       '840 ', '647 ', '191 ', '373 ', '437 ', '598 ', '716 ', '585 ',
       '982 ', '222 ', '219 ', '55 ', '948 ', '323 ', '691 ', '511 ',
       '951 ', '963 ', '25 ', '554 ', '351 ', '27 ', '82 ', '208 ',
       '913 ', '514 ', '551 ', '29 ', '103 ', '898 ', '743 ', '116 ',
       '153 ', '209 ', '353 ', '499 ', '173 ', '597 ', '809 ', '122 ',
       '411 ', '400 ', '801 ', '787 ', '237 ', '50 ', '643 ', '986 ',
       '97 ', '516 ', '837 ', '780 ', '961 ', '269 ', '20 ', '498 ',
       '600 ', '749 ', '642 ', '881 ', '72 ', '656 ', '601 ', '221 ',
       '228 ', '108 ', '940 ', '176 ', '33 ', '663 ', '34 ', '942 ',
       '259 ', '164 ', '458 ', '245 ', '629 ', '28 ', '288 ', '775 ',
       '785 ', '636 ', '916 ', '994 ', '309 ', '485 ', '914 ', '903 ',
       '608 ', '500 ', '54 ', '562 ', '847 ', '957 ', '688 ', '811 ',
       '270 ', '48 ', '329 ', '523 ', '921 ', '874 ', '981 ', '784 ',
       '280 ', '24 ', '518 ', '754 ', '892 ', '154 ', '860 ', '364 ',
       '387 ', '626 ', '161 ', '879 ', '39 ', '970 ', '170 ', '141 ',
       '160 ', '144 ', '143 ', '190 ', '376 ', '193 ', '246 ', '73 ',
       '658 ', '992 ', '253 ', '420 ', '404 ', '470 ', '226 ', '240 ',
       '89 ', '234 ', '257 ', '861 ', '467 ', '157 ', '44 ', '676 ',
       '67 ', '552 ', '885 ', '1020 ', '582 ', '619 '], dtype=object)

In [227]:
df_copy['Size'] = df_copy['Size'].str.replace('Varies with device',str(np.nan))

In [228]:
df_copy['Size'] = df_copy['Size'].astype('float')

In [229]:
df_copy['Size'].dtype

dtype('float64')

In [230]:
df_copy['Size'].isnull().sum()

1695

In [231]:
for i in df_copy['Size'] :
    if (i<10) :
        df_copy['Size'] = df_copy['Size'].replace(i,i*1000)

In [232]:
df_copy['Size'].head()

0    19000.0
1    14000.0
2     8700.0
3    25000.0
4     2800.0
Name: Size, dtype: float64

In [233]:
df_copy['Size'] = df_copy['Size']/1000

In [234]:
df_copy['Size'].unique()

array([1.90e+01, 1.40e+01, 8.70e+00, 2.50e+01, 2.80e+00, 5.60e+00,
       2.90e+01, 3.30e+01, 3.10e+00, 2.80e+01, 1.20e+01, 2.00e+01,
       2.10e+01, 3.70e+01, 2.70e+00, 5.50e+00, 1.70e+01, 3.90e+01,
       3.10e+01, 4.20e+00, 7.00e+00, 2.30e+01, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+01, 2.40e+01,      nan,
       9.40e+00, 1.50e+01, 1.00e+01, 1.20e+00, 2.60e+01, 8.00e+00,
       7.90e+00, 5.60e+01, 5.70e+01, 3.50e+01, 5.40e+01, 2.01e-01,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+01, 2.50e+00,
       1.60e+01, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+01,
       3.20e+01, 5.40e+00, 1.80e+01, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+01, 9.00e+00, 6.70e+00, 3.00e+01, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+01, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+01, 7.30e+01, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+01, 7.30e+00, 9.10e+00, 5.50e+01,
       2.30e-02, 6.50e+00, 1.50e+00, 7.50e+00, 5.10e+01, 4.10e+01,
       4.80e+01, 8.50e+00, 4.60e+01, 8.30e+00, 4.30e+00, 4.70e+00,
       3.30e+00, 4.00e+01, 7.80e+00, 8.80e+00, 6.60e+00, 5.10e+00,
       6.10e+01, 6.60e+01, 7.90e-02, 8.40e+00, 1.18e-01, 4.40e+01,
       6.95e-01, 1.60e+00, 6.20e+00, 1.80e-02, 5.30e+01, 1.40e+00,
       3.00e+00, 5.80e+00, 3.80e+00, 9.60e+00, 4.50e+01, 6.30e+01,
       4.90e+01, 7.70e+01, 4.40e+00, 4.80e+00, 7.00e+01, 6.90e+00,
       9.30e+00, 1.00e-02, 8.10e+00, 3.60e+01, 8.40e+01, 9.70e+01,
       2.00e+00, 1.90e+00, 1.80e+00, 5.30e+00, 4.70e+01, 5.56e-01,
       5.26e-01, 7.60e+01, 7.60e+00, 5.90e+01, 9.70e+00, 7.80e+01,
       7.20e+01, 4.30e+01, 7.70e+00, 6.30e+00, 3.34e-01, 3.40e+01,
       9.30e+01, 6.50e+01, 7.90e+01, 1.00e+02, 5.80e+01, 5.00e+01,
       6.80e+01, 6.40e+01, 6.70e+01, 6.00e+01, 9.40e+01, 2.32e-01,
       9.90e+01, 6.24e-01, 9.50e+01, 4.10e-02, 2.92e-01, 1.10e-02,
       8.00e+01, 1.70e+00, 7.40e+01, 6.20e+01, 6.90e+01, 7.50e+01,
       9.80e+01, 8.50e+01, 8.20e+01, 9.60e+01, 8.70e+01, 7.10e+01,
       8.60e+01, 9.10e+01, 8.10e+01, 9.20e+01, 8.30e+01, 8.80e+01,
       7.04e-01, 8.62e-01, 8.99e-01, 3.78e-01, 2.66e-01, 3.75e-01,
       1.30e+00, 9.75e-01, 9.80e-01, 4.10e+00, 8.90e+01, 6.96e-01,
       5.44e-01, 5.25e-01, 9.20e-01, 7.79e-01, 8.53e-01, 7.20e-01,
       7.13e-01, 7.72e-01, 3.18e-01, 5.80e-02, 2.41e-01, 1.96e-01,
       8.57e-01, 5.10e-02, 9.53e-01, 8.65e-01, 2.51e-01, 9.30e-01,
       5.40e-01, 3.13e-01, 7.46e-01, 2.03e-01, 2.60e-02, 3.14e-01,
       2.39e-01, 3.71e-01, 2.20e-01, 7.30e-01, 7.56e-01, 9.10e-02,
       2.93e-01, 1.70e-02, 7.40e-02, 1.40e-02, 3.17e-01, 7.80e-02,
       9.24e-01, 9.02e-01, 8.18e-01, 8.10e-02, 9.39e-01, 1.69e-01,
       4.50e-02, 4.75e-01, 9.65e-01, 9.00e+01, 5.45e-01, 6.10e-02,
       2.83e-01, 6.55e-01, 7.14e-01, 9.30e-02, 8.72e-01, 1.21e-01,
       3.22e-01, 1.00e+00, 9.76e-01, 1.72e-01, 2.38e-01, 5.49e-01,
       2.06e-01, 9.54e-01, 4.44e-01, 7.17e-01, 2.10e-01, 6.09e-01,
       3.08e-01, 7.05e-01, 3.06e-01, 9.04e-01, 4.73e-01, 1.75e-01,
       3.50e-01, 3.83e-01, 4.54e-01, 4.21e-01, 7.00e-02, 8.12e-01,
       4.42e-01, 8.42e-01, 4.17e-01, 4.12e-01, 4.59e-01, 4.78e-01,
       3.35e-01, 7.82e-01, 7.21e-01, 4.30e-01, 4.29e-01, 1.92e-01,
       2.00e-01, 4.60e-01, 7.28e-01, 4.96e-01, 8.16e-01, 4.14e-01,
       5.06e-01, 8.87e-01, 6.13e-01, 2.43e-01, 5.69e-01, 7.78e-01,
       6.83e-01, 5.92e-01, 3.19e-01, 1.86e-01, 8.40e-01, 6.47e-01,
       1.91e-01, 3.73e-01, 4.37e-01, 5.98e-01, 7.16e-01, 5.85e-01,
       9.82e-01, 2.22e-01, 2.19e-01, 5.50e-02, 9.48e-01, 3.23e-01,
       6.91e-01, 5.11e-01, 9.51e-01, 9.63e-01, 2.50e-02, 5.54e-01,
       3.51e-01, 2.70e-02, 8.20e-02, 2.08e-01, 9.13e-01, 5.14e-01,
       5.51e-01, 2.90e-02, 1.03e-01, 8.98e-01, 7.43e-01, 1.16e-01,
       1.53e-01, 2.09e-01, 3.53e-01, 4.99e-01, 1.73e-01, 5.97e-01,
       8.09e-01, 1.22e-01, 4.11e-01, 4.00e-01, 8.01e-01, 7.87e-01,
       2.37e-01, 5.00e-02, 6.43e-01, 9.86e-01, 9.70e-02, 5.16e-01,
       8.37e-01, 7.80e-01, 9.61e-01, 2.69e-01, 2.00e-02, 4.98e-01,
       6.00e-01, 7.49e-01, 6.42e-01, 8.81e-01, 7.20e-02, 6.56e-01,
       6.01e-01, 2.21e-01, 2.28e-01, 1.08e-01, 9.40e-01, 1.76e-01,
       3.30e-02, 6.63e-01, 3.40e-02, 9.42e-01, 2.59e-01, 1.64e-01,
       4.58e-01, 2.45e-01, 6.29e-01, 2.80e-02, 2.88e-01, 7.75e-01,
       7.85e-01, 6.36e-01, 9.16e-01, 9.94e-01, 3.09e-01, 4.85e-01,
       9.14e-01, 9.03e-01, 6.08e-01, 5.00e-01, 5.40e-02, 5.62e-01,
       8.47e-01, 9.57e-01, 6.88e-01, 8.11e-01, 2.70e-01, 4.80e-02,
       3.29e-01, 5.23e-01, 9.21e-01, 8.74e-01, 9.81e-01, 7.84e-01,
       2.80e-01, 2.40e-02, 5.18e-01, 7.54e-01, 8.92e-01, 1.54e-01,
       8.60e-01, 3.64e-01, 3.87e-01, 6.26e-01, 1.61e-01, 8.79e-01,
       3.90e-02, 9.70e-01, 1.70e-01, 1.41e-01, 1.60e-01, 1.44e-01,
       1.43e-01, 1.90e-01, 3.76e-01, 1.93e-01, 2.46e-01, 7.30e-02,
       6.58e-01, 9.92e-01, 2.53e-01, 4.20e-01, 4.04e-01, 4.70e-01,
       2.26e-01, 2.40e-01, 8.90e-02, 2.34e-01, 2.57e-01, 8.61e-01,
       4.67e-01, 1.57e-01, 4.40e-02, 6.76e-01, 6.70e-02, 5.52e-01,
       8.85e-01, 1.02e+00, 5.82e-01, 6.19e-01])

In [235]:
df_copy.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [236]:
df_copy.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [237]:
df_copy['Installs']

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10840, dtype: object

In [238]:
df['Installs'].dtype

dtype('O')

In [239]:
df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [240]:
df_copy['Installs'].str.replace('+','')

0            10,000
1           500,000
2         5,000,000
3        50,000,000
4           100,000
            ...
10836         5,000
10837           100
10838         1,000
10839         1,000
10840    10,000,000
Name: Installs, Length: 10840, dtype: object

In [241]:
df_copy['Price']

0        0
1        0
2        0
3        0
4        0
        ..
10836    0
10837    0
10838    0
10839    0
10840    0
Name: Price, Length: 10840, dtype: object

In [242]:
df_copy['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [243]:
char_to_remove=['+',',','$']
cols_to_clean = ['Installs','Price']
for item in char_to_remove :
    for col in cols_to_clean :
        df_copy[col] = df_copy[col].str.replace(item,'')

In [244]:
df_copy['Price'].unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [245]:
df_copy['Installs'].unique()

array(['10000', '500000', '5000000', '50000000', '100000', '50000',
       '1000000', '10000000', '5000', '100000000', '1000000000', '1000',
       '500000000', '50', '100', '500', '10', '1', '5', '0'], dtype=object)

In [246]:
df_copy['Installs'].astype('int')

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: int32

In [247]:
df_copy['Price'].astype('float')

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10836    0.0
10837    0.0
10838    0.0
10839    0.0
10840    0.0
Name: Price, Length: 10840, dtype: float64

In [248]:
df_copy['Last Updated']

0         January 7, 2018
1        January 15, 2018
2          August 1, 2018
3            June 8, 2018
4           June 20, 2018
               ...
10836       July 25, 2017
10837        July 6, 2018
10838    January 20, 2017
10839    January 19, 2015
10840       July 25, 2018
Name: Last Updated, Length: 10840, dtype: object

In [249]:
df_copy['Last Updated'] = pd.to_datetime(df_copy['Last Updated'])

In [250]:
df_copy['day'] = df_copy['Last Updated'].dt.day

In [251]:
df_copy['month'] = df_copy['Last Updated'].dt.month

In [252]:
df_copy['year'] = df_copy['Last Updated'].dt.year

In [253]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [254]:
df_copy.to_csv('google_cleaned.csv',index='False')

In [255]:
dataset = pd.read_csv('google_cleaned.csv')

In [256]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10840 non-null  int64
 1   App             10840 non-null  object
 2   Category        10840 non-null  object
 3   Rating          9366 non-null   float64
 4   Reviews         10840 non-null  int64
 5   Size            9145 non-null   float64
 6   Installs        10840 non-null  int64
 7   Type            10839 non-null  object
 8   Price           10840 non-null  float64
 9   Content Rating  10840 non-null  object
 10  Genres          10840 non-null  object
 11  Last Updated    10840 non-null  object
 12  Current Ver     10832 non-null  object
 13  Android Ver     10838 non-null  object
 14  day             10840 non-null  int64
 15  month           10840 non-null  int64
 16  year            10840 non-null  int64
dtypes: float64(3), int64(6), object(8)
memory usage: 1.4+ MB

In [257]:
dataset.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [258]:
dataset.tail()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
10835,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,25,7,2017
10836,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,6,7,2018
10837,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up,20,1,2017
10838,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,19,1,2015
10839,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,25,7,2018

In [259]:
dataset.shape

(10840, 17)

In [260]:
dataset.sample()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
9718,9718,The Visitor: Ep.1 - Kitty Cat Carnage,GAME,4.4,3017,39.0,500000,Free,0.0,Mature 17+,Adventure,2018-01-02,1.3.7,4.3 and up,2,1,2018

In [261]:
dataset.sample(5)

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
10735,10736,FP-safe,BUSINESS,NaN,0,2.6,100,Free,0.00,Everyone,Business,2018-05-08,1.0,4.0.3 and up,8,5,2018
4534,4534,R Instructor,FAMILY,4.1,135,4.9,1000,Paid,4.84,Everyone,Education,2014-02-21,2.03,3.0 and up,21,2,2014
9219,9219,TN Electricity (TNEB),LIFESTYLE,3.9,73,3.8,10000,Free,0.00,Everyone,Lifestyle,2016-12-21,8.0,2.3 and up,21,12,2016
6966,6966,Water Surfer Floating BMX Bicycle Rider Racing,FAMILY,4.4,551,38.0,100000,Free,0.00,Everyone,Simulation,2017-07-03,1.0,2.3 and up,3,7,2017
5516,5516,Moovit: Bus Time & Train Time Live Info,MAPS_AND_NAVIGATION,4.4,616742,NaN,10000000,Free,0.00,Everyone,Maps & Navigation,2018-08-05,Varies with device,Varies with device,5,8,2018

In [262]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10840 non-null  int64
 1   App             10840 non-null  object
 2   Category        10840 non-null  object
 3   Rating          9366 non-null   float64
 4   Reviews         10840 non-null  int64
 5   Size            9145 non-null   float64
 6   Installs        10840 non-null  int64
 7   Type            10839 non-null  object
 8   Price           10840 non-null  float64
 9   Content Rating  10840 non-null  object
 10  Genres          10840 non-null  object
 11  Last Updated    10840 non-null  object
 12  Current Ver     10832 non-null  object
 13  Android Ver     10838 non-null  object
 14  day             10840 non-null  int64
 15  month           10840 non-null  int64
 16  year            10840 non-null  int64
dtypes: float64(3), int64(6), object(8)
memory usage: 1.4+ MB

In [263]:
dataset.isnull().sum()

Unnamed: 0           0
App                  0
Category             0
Rating            1474
Reviews              0
Size              1695
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
day                  0
month                0
year                 0
dtype: int64

In [264]:
dataset.describe()

,Unnamed: 0,Rating,Reviews,Size,Installs,Price,day,month,year
count,10840.000000,9366.000000,1.084000e+04,9145.000000,1.084000e+04,10840.000000,10840.000000,10840.000000,10840.000000
mean,5419.533948,4.191757,4.441529e+05,21.506534,1.546434e+07,1.027368,15.609041,6.422325,2017.399723
std,3129.439605,0.515219,2.927761e+06,22.596021,8.502936e+07,15.949703,9.561621,2.578388,1.100914
min,0.000000,1.000000,0.000000e+00,0.010000,0.000000e+00,0.000000,1.000000,1.000000,2010.000000
25%,2709.750000,4.000000,3.800000e+01,4.900000,1.000000e+03,0.000000,6.000000,5.000000,2017.000000
50%,5419.500000,4.300000,2.094000e+03,13.000000,1.000000e+05,0.000000,16.000000,7.000000,2018.000000
75%,8129.250000,4.500000,5.477550e+04,30.000000,5.000000e+06,0.000000,24.000000,8.000000,2018.000000
max,10840.000000,5.000000,7.815831e+07,100.000000,1.000000e+09,400.000000,31.000000,12.000000,2018.000000

In [265]:
dataset.describe(include='all')

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
count,10840.000000,10840,10840,9366.000000,1.084000e+04,9145.000000,1.084000e+04,10839,10840.000000,10840,10840,10840,10832,10838,10840.000000,10840.000000,10840.000000
unique,NaN,9659,33,NaN,NaN,NaN,NaN,2,NaN,6,119,1377,2831,33,NaN,NaN,NaN
top,NaN,ROBLOX,FAMILY,NaN,NaN,NaN,NaN,Free,NaN,Everyone,Tools,2018-08-03,Varies with device,4.1 and up,NaN,NaN,NaN
freq,NaN,9,1972,NaN,NaN,NaN,NaN,10039,NaN,8714,842,326,1459,2451,NaN,NaN,NaN
mean,5419.533948,NaN,NaN,4.191757,4.441529e+05,21.506534,1.546434e+07,NaN,1.027368,NaN,NaN,NaN,NaN,NaN,15.609041,6.422325,2017.399723
std,3129.439605,NaN,NaN,0.515219,2.927761e+06,22.596021,8.502936e+07,NaN,15.949703,NaN,NaN,NaN,NaN,NaN,9.561621,2.578388,1.100914
min,0.000000,NaN,NaN,1.000000,0.000000e+00,0.010000,0.000000e+00,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,2010.000000
25%,2709.750000,NaN,NaN,4.000000,3.800000e+01,4.900000,1.000000e+03,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,2017.000000
50%,5419.500000,NaN,NaN,4.300000,2.094000e+03,13.000000,1.000000e+05,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,16.000000,7.000000,2018.000000
75%,8129.250000,NaN,NaN,4.500000,5.477550e+04,30.000000,5.000000e+06,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,24.000000,8.000000,2018.000000
max,10840.000000,NaN,NaN,5.000000,7.815831e+07,100.000000,1.000000e+09,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,31.000000,12.000000,2018.000000

In [266]:
dataset.duplicated9.

<bound method DataFrame.duplicated of        Unnamed: 0                                                App  \
0               0     Photo Editor & Candy Camera & Grid & ScrapBook
1               1                                Coloring book moana
2               2  U Launcher Lite – FREE Live Cool Themes, Hide ...
3               3                              Sketch - Draw & Paint
4               4              Pixel Draw - Number Art Coloring Book
...           ...                                                ...
10835       10836                                   Sya9a Maroc - FR
10836       10837                   Fr. Mike Schmitz Audio Teachings
10837       10838                             Parkinson Exercices FR
10838       10839                      The SCP Foundation DB fr nn5n
10839       10840      iHoroscope - 2018 Daily Horoscope & Astrology

                  Category  Rating  Reviews  Size  Installs  Type  Price  \
0           ART_AND_DESIGN     4.1      159  19.0     10000  Free    0.0
1           ART_AND_DESIGN     3.9      967  14.0    500000  Free    0.0
2           ART_AND_DESIGN     4.7    87510   8.7   5000000  Free    0.0
3           ART_AND_DESIGN     4.5   215644  25.0  50000000  Free    0.0
4           ART_AND_DESIGN     4.3      967   2.8    100000  Free    0.0
...                    ...     ...      ...   ...       ...   ...    ...
10835               FAMILY     4.5       38  53.0      5000  Free    0.0
10836               FAMILY     5.0        4   3.6       100  Free    0.0
10837              MEDICAL     NaN        3   9.5      1000  Free    0.0
10838  BOOKS_AND_REFERENCE     4.5      114   NaN      1000  Free    0.0
10839            LIFESTYLE     4.5   398307  19.0  10000000  Free    0.0

      Content Rating                     Genres Last Updated  \
0           Everyone               Art & Design   2018-01-07
1           Everyone  Art & Design;Pretend Play   2018-01-15
2           Everyone               Art & Design   2018-08-01
3               Teen               Art & Design   2018-06-08
4           Everyone    Art & Design;Creativity   2018-06-20
...              ...                        ...          ...
10835       Everyone                  Education   2017-07-25
10836       Everyone                  Education   2018-07-06
10837       Everyone                    Medical   2017-01-20
10838     Mature 17+          Books & Reference   2015-01-19
10839       Everyone                  Lifestyle   2018-07-25

              Current Ver         Android Ver  day  month  year
0                   1.0.0        4.0.3 and up    7      1  2018
1                   2.0.0        4.0.3 and up   15      1  2018
2                   1.2.4        4.0.3 and up    1      8  2018
3      Varies with device          4.2 and up    8      6  2018
4                     1.1          4.4 and up   20      6  2018
...                   ...                 ...  ...    ...   ...
10835                1.48          4.1 and up   25      7  2017
10836                 1.0          4.1 and up    6      7  2018
10837                 1.0          2.2 and up   20      1  2017
10838  Varies with device  Varies with device   19      1  2015
10839  Varies with device  Varies with device   25      7  2018

[10840 rows x 17 columns]>

In [267]:
dataset.shape

(10840, 17)

Exploring the data of the dataset

In [268]:
num_feature=[]
categorical_features=[]

In [280]:
# Sepearing the numerical and categorical featuresd
for i in dataset.columns :
    if (dataset[i].dtype=='O') :
        categorical_features.append(i)
    elif (dataset[i].dtype!='O'):
        num_feature.append(i)

In [281]:
print(num_feature)

['Unnamed: 0', 'Rating', 'Reviews', 'Size', 'Installs', 'Price', 'day', 'month', 'year']

In [282]:
print(categorical_features)

['App', 'Category', 'Type', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver', 'App', 'Category', 'Type', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [283]:
df['App'].value_counts()

App
ROBLOX                                                9
CBS Sports App - Scores, News, Stats & Watch Live     8
ESPN                                                  7
Duolingo: Learn Languages Free                        7
Candy Crush Saga                                      7
                                                     ..
Meet U - Get Friends for Snapchat, Kik & Instagram    1
U-Report                                              1
U of I Community Credit Union                         1
Waiting For U Launcher Theme                          1
iHoroscope - 2018 Daily Horoscope & Astrology         1
Name: count, Length: 9660, dtype: int64

In [284]:
len(df['App'].value_counts())

9660

In [285]:
df['App'].value_counts(normalize=True)

App
ROBLOX                                                0.000830
CBS Sports App - Scores, News, Stats & Watch Live     0.000738
ESPN                                                  0.000646
Duolingo: Learn Languages Free                        0.000646
Candy Crush Saga                                      0.000646
                                                        ...
Meet U - Get Friends for Snapchat, Kik & Instagram    0.000092
U-Report                                              0.000092
U of I Community Credit Union                         0.000092
Waiting For U Launcher Theme                          0.000092
iHoroscope - 2018 Daily Horoscope & Astrology         0.000092
Name: proportion, Length: 9660, dtype: float64

In [286]:
# Seeing the relation of the numerical feature using kernel distribution graph

In [ ]:
# Numerical column -> Univariant Analysis->kde